name: saadiyat
description: saadiyat app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #router
  # auto_route: ^0.6.9
  auto_route: ^1.0.0-beta.5+1

  #ui
  auto_size_text: ^2.1.0
  animated_text_kit: ^3.1.0
  sliding_sheet: ^0.4.1
  modal_bottom_sheet: ^1.0.0+1
  flutter_swiper: ^1.1.6
  flutter_easyrefresh: ^2.1.8
  flutter_easyloading: ^2.2.1
  octo_image: ^0.3.0
  cached_network_image: ^2.5.0
  convex_bottom_bar: ^2.6.0
  carousel_slider: ^2.3.1
  dots_indicator: ^1.2.0
  font_awesome_flutter: ^8.11.0
  extended_nested_scroll_view: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  google_nav_bar: ^3.1.0 
  badges: ^1.1.6
  step_progress_indicator: ^0.2.5+8
  modal_progress_hud: ^0.1.3

  #animator
  animations: ^1.1.2
  animate_do: ^1.7.5
  loading_animations: ^2.1.0
  
  #http
  dio: ^3.0.10
  retrofit: ^1.3.4+1

  #tool 
  wakelock: ^0.2.1+1
  image_picker: ^0.6.7+17
  image_cropper: ^1.3.1 
  file_picker: ^2.1.4
  url_launcher: ^5.7.10 
  json_annotation: ^3.1.1
  shared_preferences: ^0.5.12+4
  open_file: ^3.0.3 
  flutter_cache_manager: ^2.1.0
  package_info: ^0.4.3+2

  #bloc
  rxdart: ^0.24.0 
  equatable: ^1.2.5
  # flutter_bloc: ^6.1.1 
  flutter_bloc: ^5.0.1
  flutter_form_bloc: ^0.15.1
  flutter_form_builder: ^3.11.5
  # form_bloc: ^0.19.1 
  # flutter_form_bloc: ^0.19.0 
  # flutter_form_builder: ^4.1.0

  #validate
  form_field_validator: ^1.0.1

  #font
  google_fonts: ^1.1.1

  #push
  jpush_flutter: ^0.6.1
  jmessage_flutter: ^0.6.5
  # modal_progress_hud: ^0.1.3

  #map
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # flutter pub run build_runner build
  build_runner: ^1.10.11
  retrofit_generator: ^1.4.1
  # auto_route_generator: ^0.6.10
  auto_route_generator: ^1.0.0-beta.5
  json_serializable: ^3.5.1
  flutter_launcher_icons: "^0.8.0"

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  image_path_android: "assets/android_logo.png"
  image_path_ios: "assets/ios_logo.jpg"

flutter:
  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/logo.png
    - assets/1.0x/logo.png
    - assets/1.5x/logo.png

    - assets/logo-title.png
    - assets/1.0x/logo-title.png
    - assets/1.5x/logo-title.png
    
    - assets/bg.png
    - assets/1.0x/bg.png
    - assets/1.5x/bg.png

    - assets/apply.png
    - assets/1.0x/apply.png
    - assets/1.5x/apply.png

    - assets/about.png
    - assets/1.0x/about.png
    - assets/1.5x/about.png

    - assets/header.png 
    - assets/1.0x/header.png
    - assets/1.5x/header.png

    - assets/banner1.jpg 
    - assets/1.0x/banner1.jpg
    - assets/1.5x/banner1.jpg

    - assets/banner2.jpg 
    - assets/1.0x/banner2.jpg
    - assets/1.5x/banner2.jpg

    - assets/banner3.jpg 
    - assets/1.0x/banner3.jpg
    - assets/1.5x/banner3.jpg

    - assets/banner4.jpg 
    - assets/1.0x/banner4.jpg
    - assets/1.5x/banner4.jpg

    - assets/banner5.jpg 
    - assets/1.0x/banner5.jpg
    - assets/1.5x/banner5.jpg

    - assets/banner6.jpg 
    - assets/1.0x/banner6.jpg
    - assets/1.5x/banner6.jpg
    
    - assets/user.png
    - assets/nodata.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
