import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedLogin {
  final List<LoginModel> results;

  AutogeneratedLogin({this.results});

  factory AutogeneratedLogin.fromJson(Map<String, dynamic> json) {
    List<LoginModel> temp;
    if (json['results'] != null) {
      temp = <LoginModel>[];
      json['results'].forEach((v) {
        temp.add(LoginModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedLogin(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class LoginModel extends Equatable {
  final int id;
  final String name;

  LoginModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory LoginModel.fromJson(Map<String, dynamic> json) {
    return LoginModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
