import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedIndex {
  final List<IndexModel> results;

  AutogeneratedIndex({this.results});

  factory AutogeneratedIndex.fromJson(Map<String, dynamic> json) {
    List<IndexModel> temp;
    if (json['results'] != null) {
      temp = <IndexModel>[];
      json['results'].forEach((v) {
        temp.add(IndexModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedIndex(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class IndexModel extends Equatable {
  final int id;
  final String name;

  IndexModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory IndexModel.fromJson(Map<String, dynamic> json) {
    return IndexModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
